name: CD

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           script: |
             npm install
             npm test
   
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.PRIVATE_KEY }}
         port: 22
         script: |
           cd /home/mi/app/service-base64
           git pull origin main
           git status
           export NVM_DIR=~/.nvm
           source ~/.nvm/nvm.sh
           npm install
           pm2 restart test
